### ISSUE TITLE
Question: RXJava2 Resources.

### ISSUE THREAD

**Issue by Ajimi** [TonnyL/Espresso#14]
I'm wondering where did you learn all of this RXJAVA2?  
Can you please provide us with some good resources or anything that could help a beginner to understand more RXJAVA2. 
I did a lot of research I didn't find useful tutorials the only thing that I found is your repository.

**Comment by wbinarytree** [comment]
@Ajimi  You could start with some Youtube video. 
https://www.youtube.com/watch?v=htIXKI5gOQU
https://www.youtube.com/watch?v=XLH2v9deew0&t=1596s

**Comment by TonnyL** [comment]
@Ajimi Hi

Yeah,  @wbinarytree helps me a lot about the rxjava. He will give you some advice. Happy coding!

BTW, are u Chinese?

**Comment by Ajimi** [comment]
Thank you a lot for fast responding I really appreciate your work it's an honor. @wbinarytree I already watched them. do you have a specific book or another android project?. I would be grateful if you provide me with RXJava2 rather than RXJava1. Thanks.

**Comment by Ajimi** [comment]
@TonnyL I'm from TUNISIA and I'm following this project from the starting point. I wish that I'm Chinese I would understand a lot of open source projects hahaha . BTW my next aim is to learn the Chinese language.
![flag_of_tunisia svg](https://cloud.githubusercontent.com/assets/9468146/26724858/d8ebb9d8-479b-11e7-9cc4-515b9a1b1949.png)

**Comment by wbinarytree** [comment]
@Ajimi as A beginner I hope you should just understand clearly with reactive and functional programming . You could see this video as well : https://www.youtube.com/watch?v=f3acAsSZPhU.  I don't really know there is a book for those stuff, Sorry. And After that , if you already confidence with Rx, you can learn more from david's (Which is the main Collaborators for RxJava currently) blog :http://akarnokd.blogspot.fr/

**Comment by TonnyL** [comment]
@Ajimi Got it.
I wondered that because I saw that you have starred some repos whose description are in Chinese. This project Espresso is my first time using RxJava(2), before I started it, I had found some useful and awesome articles about rxjava, but they are in Chinese. So if you can read Chinese, they will be nice. 
BTW, fighting in learning Chinese! (My English sucks, and my aim is learning English well🌚)

**Comment by Ajimi** [comment]
@TonnyL Google Translate works well for me at least I can understand 60% of what is written.
Send me those articles I will try to figure out what to do I know that Chinese people are professional in explaining new things. And your English looks fine you're good.

**Comment by TonnyL** [comment]
@Ajimi http://www.jianshu.com/p/464fa025229e. Here it is. it is a series and you could find the other articles at [the home page of the author](http://www.jianshu.com/u/c50b715ccaeb). And this [repo](https://github.com/MindorksOpenSource/android-mvp-architecture) seems good.
