### ISSUE TITLE
Any release or download?

### ISSUE THREAD

**Issue by JokerQyou** [TonnyL/Espresso#15]
Hi. First thank you for providing another package tracker app for Android. The design looks really good to me. But I'm not (yet) an Android programmer, so may I ask if there's any kind of releases? Say, what is the Play Store link of this app? Or would you provide APK download via Github release?

Have a nice day.

**Comment by TonnyL** [comment]
Sorry, no apk yet. But I recommend you download another one if you want to use it daily. Click [here](https://play.google.com/store/apps/details?id=info.papdt.express.helper).
