### ISSUE TITLE
cannot resolve symbol 'MATRIX_SAVE_FLAG'

### ISSUE THREAD

**Issue by codergu64** [TonnyL/Espresso#18]
![图片](https://user-images.githubusercontent.com/42142946/56556216-f6811f80-65c9-11e9-932c-8ee59520b8ef.png)

**Comment by TonnyL** [comment]
<img width="1174" alt="Screen Shot 2019-04-23 at 1 59 15 PM" src="https://user-images.githubusercontent.com/13329148/56558077-07cd2a80-65d0-11e9-9c81-00f1e5be07ef.png">

It seems like that you haven't import the class correctly. The complete class name is `android.graphics.Canvas` and the constant `MATRIX_SAVE_FLAG` is defined at line 317(sdk 28).

**Comment by TonnyL** [comment]
@CVProgramer Any other question? If the answer is negative, I'll close this issue later. Feel free to reply or just file another one.

**Comment by codergu64** [comment]
Thanks for your answer!




------------------ Original ------------------
