### ISSUE TITLE
the bottom tab issues

### ISSUE THREAD

**Issue by FlogFly** [TonnyL/Espresso#5]
when you click the search icon on the title bar ,into the search activity, the keyboard is show,than you close the activity , you will see the MainActivity 's bottom tab is above on the keyboard, when the keyboard is dismiss, than the bottom tab down.

**Comment by TonnyL** [comment]
It may be a bug(But it does not appear on my own phone with Android 7.1.1). Anyway, I will fix it.

**Comment by TonnyL** [comment]
Fixed. If you find any other problem about it, DO NOT hesitate to reopen this issue or just open another one. Happy coding😃!
