### ISSUE TITLE
Zxing library

### ISSUE THREAD

**Issue by Ajimi** [TonnyL/Espresso#6]
How do I make the CaptureActivity able to scan QRCode ?

**Comment by TonnyL** [comment]
You could see the code of [CaptureActivity](https://github.com/TonnyL/Espresso/blob/master/mobile/src/main/java/io/github/marktony/espresso/zxing/CaptureActivity.java) as a reference.
See [this issue](https://github.com/TonnyL/Espresso/issues/2) for more information.

**Comment by TonnyL** [comment]
Hi, @Ajimi .

Have you solve the problem yet. If your answer is positive, then I will close this issue. Or we can discuss the way to solve it.

**Comment by Ajimi** [comment]
It works fine with bar code but qr code doesn't work.
